package com.wenting.mediaserver.protocol.webrtc.dtls;

public enum DtlsTransportState {
    NEW,
    CLIENT_HELLO_RECEIVED,
    SERVER_HELLO_PREPARED,
    SERVER_HELLO_SENT,
    CLIENT_KEY_EXCHANGE_RECEIVED,
    CHANGE_CIPHER_SPEC_RECEIVED,
    FINISHED_RECEIVED,
    HANDSHAKE_COMPLETE,
    SRTP_KEYING_EXPORTED
}
